import type { CharacterId, CharacterProfile } from "../types/character"

export const CHARACTERS: Record<CharacterId, CharacterProfile> = {
  coco: {
    name: "Coco",
    role: "el loro de la vecina",
    definingTrait: "Curioso",
    personality: "Entusiasta, paciente y juguetón; quiere que el estudiante gane autonomía.",
    motivation: "Acompañar al estudiante hasta que pueda desenvolverse por su cuenta.",
    relationship: "Compañero y tutor narrativo del estudiante.",
    speechStyle: "Español breve y alentador; modela inglés claro sin resolver el reto por el estudiante.",
    narrativeFunction: "Acompañar toda la historia y orientar el aprendizaje.",
    visual: { species: "parrot", skin: "#1f9d55", hair: "#dc2626", shirt: "#facc15", background: "#dcfce7", hairStyle: "crest", accessory: "none" },
  },
  marta: {
    name: "Marta", role: "tu vecina", definingTrait: "Acogedora",
    personality: "Práctica y protectora.", motivation: "Quiere que el recién llegado se adapte al barrio.",
    relationship: "Vecina y primera aliada del estudiante.", speechStyle: "Cercana, directa y tranquilizadora.",
    narrativeFunction: "Conectar al estudiante con oportunidades.",
    visual: { species: "human", skin: "#e8b48a", hair: "#40261a", shirt: "#0d9488", background: "#e0f2fe", hairStyle: "bun", accessory: "earrings" },
  },
  nico: {
    name: "Nico", role: "el vendedor del mercado", definingTrait: "Ingenioso",
    personality: "Enérgico y servicial.", motivation: "Quiere ayudar a sus clientes a decidir con confianza.",
    relationship: "Vendedor del mercado que ayuda al estudiante.", speechStyle: "Rápida, concreta y amistosa.",
    narrativeFunction: "Introducir intercambios cotidianos.",
    visual: { species: "human", skin: "#c98a5e", hair: "#1f2937", shirt: "#f59e0b", background: "#fef3c7", hairStyle: "short", accessory: "none" },
  },
  beto: {
    name: "Don Beto", role: "el señor que te orienta", definingTrait: "Paciente",
    personality: "Observador y generoso.", motivation: "Disfruta orientar a quienes no conocen el barrio.",
    relationship: "Vecino mayor que orienta al estudiante.", speechStyle: "Pausada, clara y basada en referencias sencillas.",
    narrativeFunction: "Enseñar a ubicarse en la ciudad.",
    visual: { species: "human", skin: "#dfa77a", hair: "#9ca3af", shirt: "#a16207", background: "#fef9c3", hairStyle: "bald", accessory: "glasses" },
  },
  cami: {
    name: "Cami", role: "la chica del café", definingTrait: "Sociable",
    personality: "Atenta y optimista.", motivation: "Quiere que cada persona se sienta bienvenida.",
    relationship: "Chica del café que conversa con el estudiante.", speechStyle: "Cálida, natural y expresiva.",
    narrativeFunction: "Facilitar conversaciones sociales.",
    visual: { species: "human", skin: "#f2c9a0", hair: "#7c2d12", shirt: "#0ea5e9", background: "#e0f2fe", hairStyle: "curly", accessory: "earrings" },
  },
  chofer: {
    name: "El chofer", role: "el chofer del bus", definingTrait: "Preciso",
    personality: "Responsable y ordenado.", motivation: "Quiere que los pasajeros lleguen sin confundirse.",
    relationship: "Chofer del bus que ayuda al estudiante a trasladarse.", speechStyle: "Breve, informativa y sin rodeos.",
    narrativeFunction: "Introducir rutas, horarios y boletos.",
    visual: { species: "human", skin: "#8d5524", hair: "#111827", shirt: "#1d4ed8", background: "#dbeafe", hairStyle: "short", accessory: "cap" },
  },
  rosa: {
    name: "Rosa", role: "la señora de la lavandería", definingTrait: "Metódica",
    personality: "Paciente y resolutiva.", motivation: "Quiere que la lavandería funcione sin complicaciones.",
    relationship: "Encargada de la lavandería que guía al estudiante.", speechStyle: "Secuencial, práctica y amable.",
    narrativeFunction: "Guiar procesos cotidianos.",
    visual: { species: "human", skin: "#d9a06b", hair: "#6b7280", shirt: "#be185d", background: "#fce7f3", hairStyle: "bun", accessory: "glasses" },
  },
  sergio: {
    name: "Sergio", role: "el dueño del departamento", definingTrait: "Responsable",
    personality: "Pragmático y confiable.", motivation: "Quiere mantener el departamento en buenas condiciones.",
    relationship: "Dueño del departamento que acuerda con el estudiante.", speechStyle: "Serena, concreta y orientada a soluciones.",
    narrativeFunction: "Introducir llamadas y acuerdos.",
    visual: { species: "human", skin: "#e8b48a", hair: "#374151", shirt: "#4b5563", background: "#e5e7eb", hairStyle: "short", accessory: "beard" },
  },
  sofia: {
    name: "Sofía", role: "tu jefa", definingTrait: "Exigente",
    personality: "Profesional y justa.", motivation: "Busca personas responsables para su equipo.",
    relationship: "Jefa que orienta al estudiante en el trabajo.", speechStyle: "Formal, clara y respetuosa.",
    narrativeFunction: "Introducir el entorno laboral y sus expectativas.",
    visual: { species: "human", skin: "#f0c8a0", hair: "#1c1917", shirt: "#7c3aed", background: "#ede9fe", hairStyle: "long", accessory: "none" },
  },
  tere: {
    name: "Tere", role: "tu compañera de trabajo", definingTrait: "Colaborativa",
    personality: "Extrovertida y solidaria.", motivation: "Quiere integrar al estudiante al equipo y a la vida social.",
    relationship: "Compañera de trabajo que acompaña al estudiante.", speechStyle: "Conversacional, espontánea y alentadora.",
    narrativeFunction: "Conectar empleo, amistad y pertenencia.",
    visual: { species: "human", skin: "#c98a5e", hair: "#111827", shirt: "#16a34a", background: "#dcfce7", hairStyle: "long", accessory: "glasses" },
  },
}
