import type { CharacterConfig, CharacterId } from '../types/character';

export const CHARACTERS: Record<CharacterId, CharacterConfig> = {
  coco: {
    role: "el loro de la vecina",
    name: 'Coco',
    species: 'parrot',
    skin: '#1f9d55',
    hair: '#dc2626',
    shirt: '#facc15',
    background: '#dcfce7',
    hairStyle: 'crest',
    accessory: 'none',
  },
  marta: {
    role: "tu vecina",
    name: 'Marta',
    species: 'human',
    skin: '#e8b48a',
    hair: '#40261a',
    shirt: '#0d9488',
    background: '#e0f2fe',
    hairStyle: 'bun',
    accessory: 'earrings',
  },
  nico: {
    role: "el vendedor del mercado",
    name: 'Nico',
    species: 'human',
    skin: '#c98a5e',
    hair: '#1f2937',
    shirt: '#f59e0b',
    background: '#fef3c7',
    hairStyle: 'short',
    accessory: 'none',
  },
  beto: {
    role: "el señor que te orienta",
    name: 'Don Beto',
    species: 'human',
    skin: '#dfa77a',
    hair: '#9ca3af',
    shirt: '#a16207',
    background: '#fef9c3',
    hairStyle: 'bald',
    accessory: 'glasses',
  },
  cami: {
    role: "la chica del café",
    name: 'Cami',
    species: 'human',
    skin: '#f2c9a0',
    hair: '#7c2d12',
    shirt: '#0ea5e9',
    background: '#e0f2fe',
    hairStyle: 'curly',
    accessory: 'earrings',
  },
  chofer: {
    role: "el chofer del bus",
    name: 'El chofer',
    species: 'human',
    skin: '#8d5524',
    hair: '#111827',
    shirt: '#1d4ed8',
    background: '#dbeafe',
    hairStyle: 'short',
    accessory: 'cap',
  },
  rosa: {
    role: "la señora de la lavandería",
    name: 'Rosa',
    species: 'human',
    skin: '#d9a06b',
    hair: '#6b7280',
    shirt: '#be185d',
    background: '#fce7f3',
    hairStyle: 'bun',
    accessory: 'earrings',
  },
  sergio: {
    role: "el dueño del departamento",
    name: 'Sergio',
    species: 'human',
    skin: '#e8b48a',
    hair: '#374151',
    shirt: '#4b5563',
    background: '#e5e7eb',
    hairStyle: 'short',
    accessory: 'beard',
  },
  sofia: {
    role: "tu jefa",
    name: 'Sofía',
    species: 'human',
    skin: '#f0c8a0',
    hair: '#1c1917',
    shirt: '#7c3aed',
    background: '#ede9fe',
    hairStyle: 'long',
    accessory: 'none',
  },
  tere: {
    role: "tu compañera de trabajo",
    name: 'Tere',
    species: 'human',
    skin: '#c98a5e',
    hair: '#111827',
    shirt: '#16a34a',
    background: '#dcfce7',
    hairStyle: 'curly',
    accessory: 'earrings',
  },
};
